name: Deploy ECS Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World Test
        run: echo "GitHub Actions is working"
