name: Deploy ECS Application

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

- name: Build Docker Image
  run: |
    docker build \
    --platform linux/amd64 \
    -t ecs-demo-app \
    ./app
     
 - name: Tag Docker Image
        run: |
          docker tag ecs-demo-app:latest \
          945488515946.dkr.ecr.ap-south-1.amazonaws.com/ecs-demo-app:latest

      - name: Push Image to ECR
        run: |
          docker push \
          945488515946.dkr.ecr.ap-south-1.amazonaws.com/ecs-demo-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
          --cluster ecs-demo-cluster \
          --service ecs-demo-service \
          --force-new-deployment
